#!/bin/sh
# Generate host keys if missing
[ -f /etc/ssh/ssh_host_ed25519_key ] || \
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N '' -q
[ -f /etc/ssh/ssh_host_rsa_key ] || \
    ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N '' -q

exec /usr/sbin/sshd -D -e
