#!/bin/sh
# mkrepokey.sh — (re)generate src/bpm-rs/src/repokey.rs from an ECDSA P-256 keypair.
#
# Usage: tools/mkrepokey.sh [signing-key.pem]
#   Default key: ~/.config/bpm/repo-signing-key.pem (generated if absent).
#   Extracts the uncompressed public point (0x04 || X || Y, 65 bytes) and
#   writes it as a Rust byte array into src/bpm-rs/src/repokey.rs. Rebuild bpm.
#
# The PRIVATE key never enters the repo; only the public point is baked in.

set -eu
KEY="${1:-$HOME/.config/bpm/repo-signing-key.pem}"
HERE=$(unset CDPATH; cd -- "$(dirname -- "$0")" && pwd)
OUT="$HERE/../src/bpm-rs/src/repokey.rs"

command -v openssl >/dev/null 2>&1 || { echo "mkrepokey: need openssl" >&2; exit 1; }

if [ ! -f "$KEY" ]; then
    mkdir -p "$(dirname -- "$KEY")"
    openssl ecparam -name prime256v1 -genkey -noout -out "$KEY"
    chmod 600 "$KEY"
    echo "mkrepokey: generated $KEY"
fi

HEX=$(openssl ec -in "$KEY" -text -noout 2>/dev/null \
    | sed -n '/pub:/,/ASN1 OID/p' | grep -E '^[[:space:]]+[0-9a-f]{2}:' \
    | tr -d ' :\n')
[ "$(( ${#HEX} / 2 ))" -eq 65 ] || { echo "mkrepokey: expected 65-byte point, got $(( ${#HEX} / 2 ))" >&2; exit 1; }

{
    echo "//! repokey.rs — baked-in repository signing public key (ECDSA P-256)."
    echo "//!"
    echo "//! Auto-generated by tools/mkrepokey.sh from the maintainer keypair. The"
    echo "//! matching PRIVATE key lives outside this repo and signs bpm.index"
    echo "//! (tools/mkrepo.sh / blueberry-repo-sync). bpm verifies signatures against"
    echo "//! this key (src/sig.rs). To rotate, rerun tools/mkrepokey.sh and rebuild bpm."
    echo "//!"
    echo "//! Uncompressed EC point: 0x04 || X(32) || Y(32) = 65 bytes."
    echo ""
    echo "pub(crate) const REPO_PUBKEY: [u8; 65] = ["
    # 16 bytes per line, never splitting a 0xNN token.
    printf '%s\n' "$HEX" | awk '{
        line = "    ";
        for (i = 1; i <= length($0); i += 2) {
            line = line sprintf("0x%s, ", substr($0, i, 2));
            if ((i + 1) % 32 == 0) { print line; line = "    "; }
        }
        if (line != "    ") print line;
    }'
    echo "];"
} > "$OUT"

echo "mkrepokey: wrote $OUT"
