#!/bin/sh
# mkrepokey.sh — (re)generate src/bpm/repokey.h from an ECDSA P-256 keypair.
#
# Usage: tools/mkrepokey.sh [signing-key.pem]
#   Default key: ~/.config/bpm/repo-signing-key.pem (generated if absent).
#   Extracts the uncompressed public point (0x04 || X || Y, 65 bytes) and
#   writes it as a C byte array into src/bpm/repokey.h. Rebuild bpm afterwards.
#
# The PRIVATE key never enters the repo; only the public point is baked in.

set -eu
KEY="${1:-$HOME/.config/bpm/repo-signing-key.pem}"
HERE=$(unset CDPATH; cd -- "$(dirname -- "$0")" && pwd)
OUT="$HERE/../src/bpm/repokey.h"

command -v openssl >/dev/null 2>&1 || { echo "mkrepokey: need openssl" >&2; exit 1; }

if [ ! -f "$KEY" ]; then
    mkdir -p "$(dirname -- "$KEY")"
    openssl ecparam -name prime256v1 -genkey -noout -out "$KEY"
    chmod 600 "$KEY"
    echo "mkrepokey: generated $KEY"
fi

HEX=$(openssl ec -in "$KEY" -text -noout 2>/dev/null \
    | sed -n '/pub:/,/ASN1 OID/p' | grep -E '^[[:space:]]+[0-9a-f]{2}:' \
    | tr -d ' :\n')
[ "$(( ${#HEX} / 2 ))" -eq 65 ] || { echo "mkrepokey: expected 65-byte point, got $(( ${#HEX} / 2 ))" >&2; exit 1; }

{
    echo "/* repokey.h — baked-in repository signing public key (ECDSA P-256)."
    echo " *"
    echo " * Auto-generated by tools/mkrepokey.sh from the maintainer keypair. The"
    echo " * matching PRIVATE key lives outside this repo and is used by"
    echo " * tools/mkrepo.sh / blueberry-repo-sync to sign bpm.index. bpm verifies"
    echo " * signatures against this key (src/bpm/sig.c). To rotate, rerun"
    echo " * tools/mkrepokey.sh and rebuild bpm."
    echo " *"
    echo " * Uncompressed EC point: 0x04 || X(32) || Y(32) = 65 bytes."
    echo " */"
    echo "#ifndef BPM_REPOKEY_H"
    echo "#define BPM_REPOKEY_H"
    echo "#include <stddef.h>"
    echo ""
    echo "static const unsigned char bpm_repo_pubkey[] = {"
    printf '%s' "$HEX" | sed 's/\(..\)/0x\1, /g' | fold -w 72 | sed 's/^/    /'
    echo ""
    echo "};"
    echo "static const size_t bpm_repo_pubkey_len = sizeof bpm_repo_pubkey;"
    echo ""
    echo "#endif /* BPM_REPOKEY_H */"
} > "$OUT"

echo "mkrepokey: wrote $OUT"
